### ISSUE TITLE
Access violation on title screen

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/PlayerTrack#71]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Dalamud.DrunkenToad.GameObjectExtensions.IsValidPlayerCharacter(Dalamud.Game.ClientState.Objects.Types.GameObject)
   at PlayerTrack.ActorManager.<GetPlayerCharacters>b__20_0(Dalamud.Game.ClientState.Objects.Types.GameObject)
   at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToList()
   at PlayerTrack.ActorManager.GetPlayerCharacters()
   at PlayerTrack.ActorManager.OnTimerElapsed(System.Object, System.Timers.ElapsedEventArgs)
   at System.Timers.Timer.MyTimerCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by kalilistic** [comment]
Fixed with v3.
