### ISSUE TITLE
Fix load player bug

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/PlayerTrack#78]
2022-08-14 13:21:11.278 +02:00 [ERR] [PlayerTrack] Failed to initialize plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PlayerTrack.PlayerService.SetDerivedFields(Player player)
   at PlayerTrack.PlayerService.LoadPlayers()
   at PlayerTrack.PlayerService..ctor(PlayerTrackPlugin plugin)
   at PlayerTrack.PlayerTrackPlugin.<.ctor>b__5_0()

**Comment by kalilistic** [comment]
Fixed with v3.
