### ISSUE TITLE
Context Menu bug on characters list

### ISSUE THREAD

**Issue by Lynesth** [kalilistic/PlayerTrack#95]
Right clicking a character in the list (before loging in) throws the following exception:
```
ERR [Dalamud.ContextMenu] [Dalamud.ContextMenu] Exception in OpenMenuDetour
System.NullReferenceException: Object reference not set to an instance of an object.
   at PlayerTrack.ContextMenuManager.OpenGameObjectContextMenu(GameObjectContextMenuOpenArgs args) in /work/repo/src/PlayerTrack/PlayerTrack/Plugin/Manager/ContextMenuManager.cs:line 73
   at Dalamud.ContextMenu.DalamudContextMenu.PopulateItems(IntPtr addon, IntPtr agent, GameObjectContextMenuOpenEventDelegate normalAction, InventoryContextMenuOpenEventDelegate inventoryAction, IReadOnlyCollection`1 nativeItems)
```

**Comment by Aireil** [comment]
Yes, this has been KNOWN by kal for NEARLY A YEAR.
This dev is LAZY 😔 .
![image](https://user-images.githubusercontent.com/33433913/220147862-a1a022eb-0540-4680-bcd8-77379dfd398f.png)

**Comment by kalilistic** [comment]
Fixed with v3.
